### PR TITLE
react server rendering support

### PR DESCRIPTION
**Pull request by mipearson**

### CODE REVIEW

**Comment by zacksiri** [comment]
looking forward to this.

**Comment by rohandey** [comment]
Expected release date? Eagerly waiting for this :)

**Comment by mipearson** [comment]
Soon(tm)

We have a requirement for this at Marketplacer in an upcoming project, so I might be moving this to prime time..

**Comment by guilleiguaran** [comment]
This looks great but IMO this should be in a gem not in the core of webpack-rails, just my 2 cents 😬

**Comment by mipearson** [comment]
@guilleiguaran thought about that - but from a bit of polling I've found that almost all of the users of webpack-rails are using it to enable react (including us), so may as well support the most common use case rather than dealing with multi-repo problems.

**Comment by rohandey** [comment]
Is it ready? If yes any docs available :)

**Comment by mipearson** [comment]
I won't be merging this - I've switched to using webpacker & react-rails to solve this problem.

**Pull request closed without merging**
